#!/bin/bash
#
# @author Guilherme N. Ramos (gnramos@unb.br)
#
# Runs tests. There are 2 options:
#
# ./test     - which runs a simple test with a medium layout and 2 ghosts
# ./test all - which runs all possible configurations of layouts and ghosts
#              (may take a while....)

# Test configurations
ADAPTER="adapter.py"
CONTROLLER="controller.py"
AGENT_OPTIONS="--ghost-agent ai"
ITERATION_OPTIONS="--learn-num 2 --test-num 1"

function setup_options {
	EXP="$LAYOUT $NUM_GHOSTS ghosts"
	LAYOUT_OPTIONS="--layout $LAYOUT --num-ghosts $NUM_GHOSTS"
	OPTIONS="$AGENT_OPTIONS $ITERATION_OPTIONS $LAYOUT_OPTIONS"
}

function add_policy {
	POLICY_FILE="$LAYOUT-$NUM_GHOSTS.pol"
	rm -f $POLICY_FILE
	OPTIONS="$OPTIONS --policy-file $POLICY_FILE"
	EXP="$EXP with policy"
}

function process {
	echo -e "\n\n$EXP\n"

	python2 $CONTROLLER & pid_controller=$!
	python2 $ADAPTER $OPTIONS & pid_adapter=$!
	wait $pid_adapter
	kill $pid_controller
}

function test_with_current_setup {
	setup_options
	process

	add_policy
	process

	EXP="$EXP (existing file)"
	process
}

if [ "$1" == "all" ]; then
	for LAYOUT in "medium" "classic"
	do
		for NUM_GHOSTS in "1" "2" "3" "4"
		do
			test_with_current_setup
		done
	done
else
	LAYOUT="medium"
	NUM_GHOSTS="2"
	test_with_current_setup
fi
