#!/bin/bash
#
# @author Guilherme N. Ramos (gnramos@unb.br)
#
# Runs tests. There are 4 options:
#
# ./test             - runs a simple test with a medium layout and 2 ghosts
# ./test classic     - runs a simple test with the classic layout and 4 ghosts
# ./test all layout  - runs all combinations for Pac-Man and 2 Ghosts on the
#                      given layout
# ./test all         - runs all possible configurations of layouts and ghosts
#                      (may take a while....)


ADAPTER="adapter.py"
CONTROLLER="controller.py"

function setup_options {
	EXP="[${LAYOUT}] ${PACMAN} Pac-Man X ${NUM_GHOSTS} ${GHOST} ghosts"
	AGENT_OPTIONS="--ghost-agent ${GHOST} --pacman-agent ${PACMAN}"
	ITERATION_OPTIONS="--learn-num 2 --test-num 1"
	LAYOUT_OPTIONS="--layout ${LAYOUT} --num-ghosts ${NUM_GHOSTS}"
	OPTIONS="${AGENT_OPTIONS} ${ITERATION_OPTIONS} ${LAYOUT_OPTIONS}"
}

function add_policy {
	POLICY_FILE="${PACMAN}_${LAYOUT}_${NUM_GHOSTS}_${GHOST}.pol"
	rm -f ${POLICY_FILE}
	OPTIONS="${OPTIONS} --policy-file ${POLICY_FILE}"
	EXP="${EXP} with policy"
}

function process {
	echo -e "\n\n${EXP}\n"

	python2 ${CONTROLLER} & pid_controller=$!
	python2 ${ADAPTER} ${OPTIONS} & pid_adapter=$!
	wait ${pid_adapter} > /dev/null 2>&1
	kill ${pid_controller}
}

function test_with_current_setup {
	setup_options
	process

	add_policy
	process

	EXP="${EXP} (${POLICY_FILE})"
	process
}

TEST="${1}"
LAYOUT="${2}"
if [ "${TEST}" = "all" ]; then
	if [ -n "${LAYOUT}" ]; then
		NUM_GHOSTS="2"
		for GHOST in "random" "ai"; do
			for PACMAN in "random" "ai" "eater"; do
				test_with_current_setup
			done
		done
	else
		for LAYOUT in "medium" "classic"; do
			for GHOST in "random" "ai"; do
				for PACMAN in "random " "ai" "eater"; do
					for NUM_GHOSTS in "1" "2" "3" "4"; do
						test_with_current_setup
					done
				done
			done
		done
	fi
else
	if [ "${TEST}" = "classic" ]; then
		PACMAN="eater"
		LAYOUT="classic"
		NUM_GHOSTS="4"
		GHOST="ai"
		test_with_current_setup
	else
		PACMAN="random"
		LAYOUT="medium"
		NUM_GHOSTS="2"
		GHOST="ai"
		test_with_current_setup
	fi
fi
