#!/bin/bash
#
# http://stackoverflow.com/questions/2694588/fork-two-processes-and-kill-the-second-when-the-first-is-done

# Basic testing for all experiments (may take a while....)
ADAPTER="adapter.py"
CONTROLLER="controller.py"
AGENT_OPTIONS="--ghost-agent ai --pacman-agent ai"
ITERATION_OPTIONS="--learn-num 2 --test-num 1"

for LAYOUT in "medium" "classic"
do
	for NUM_GHOSTS in "1" "2" "3" "4"
	do
		EXP="$LAYOUT $NUM_GHOSTS ghosts"
		POLICY_FILE="$LAYOUT-$NUM_GHOSTS.pol"
		POLICY_OPTIONS="--policy-file $POLICY_FILE"
		LAYOUT_OPTIONS="--layout $LAYOUT --num-ghosts $NUM_GHOSTS"
		OPTIONS="$AGENT_OPTIONS $ITERATION_OPTIONS $LAYOUT_OPTIONS"

		echo -e "\n\n$EXP\n"

		python2 $CONTROLLER & pid_controller=$!
		python2 $ADAPTER $OPTIONS & pid_adapter=$!
		wait $pid_adapter
		kill $pid_controller

		echo -e "\n\n$EXP with new policies\n"
		rm -f $POLICY_FILE
		python2 $CONTROLLER & pid_controller=$!
		python2 $ADAPTER $OPTIONS $POLICY_OPTIONS & pid_adapter=$!
		wait $pid_adapter
		kill $pid_controller

		echo -e "\n\n$EXP with existing policy file\n"
		python2 $CONTROLLER & pid_controller=$!
		python2 $ADAPTER $OPTIONS $POLICY_OPTIONS & pid_adapter=$!
		wait $pid_adapter
		kill $pid_controller
	done
done
