#!/bin/bash
#
# http://stackoverflow.com/questions/2694588/fork-two-processes-and-kill-the-second-when-the-first-is-done

# Basic testing for all experiments (may take a while....)
ADAPTER="simulator.py"
CONTROLLER="controller.py"
AGENT_OPTIONS="--ghost-agent ai --pacman-agent ai"
ITERATION_OPTIONS="--learn-num 2 --test-num 1"
POLICY_OPTIONS="--policy-file $POLICY_FILE"

OPTIONS="$AGENT_OPTIONS $ITERATION_OPTIONS"

for EXP in "1" "2" "3" "4" "5" "6"
do
	echo -e "\n\nExperiment $EXP"
	python2 $CONTROLLER & pid_controller=$!
	python2 $ADAPTER $OPTIONS -e $EXP & pid_adapter=$!
	wait $pid_adapter
	kill $pid_controller

	echo -e "\n\nExperiment $EXP with policy --"
	$POLICY_FILE="experiment_$EXP.pol"
	rm -f $POLICY_FILE
	python2 $CONTROLLER & pid_controller=$!
	python2 $ADAPTER $OPTIONS -e $EXP $POLICY_OPTIONS & pid_adapter=$!
	wait $pid_adapter
	kill $pid_controller

	echo -e "\n\nExperiment $EXP test with existing Policy file"
	python2 $CONTROLLER & pid_controller=$!
	python2 $ADAPTER $OPTIONS -e $EXP $POLICY_OPTIONS & pid_adapter=$!
	wait $pid_adapter
	kill $pid_controller
done
